jdbc.driverClassName = org.hsqldb.jdbcDriver
jdbc.url = jdbc:hsqldb:file:${user.home}/NetBeansProjects/Niddah/BD/testdb;shutdown=true
jdbc.username = SA
jdbc.password = 
hibernate.dialect = org.hibernate.dialect.HSQLDialect
hibernate.show_sql = true
hibernate.format_sql = true
mail.username=michel.jetest@gmail.com
mail.password=Extelia123